// Code generated by mockery. DO NOT EDIT.

package time

import (
	context "context"

	porttime "github.com/amirhossein-jamali/auth-guardian/internal/domain/port/time"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTimeProvider is an autogenerated mock type for the Provider type
type MockTimeProvider struct {
	mock.Mock
}

type MockTimeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimeProvider) EXPECT() *MockTimeProvider_Expecter {
	return &MockTimeProvider_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: t, d
func (_m *MockTimeProvider) Add(t time.Time, d time.Duration) time.Time {
	ret := _m.Called(t, d)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(time.Time, time.Duration) time.Time); ok {
		r0 = rf(t, d)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTimeProvider_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockTimeProvider_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - t time.Time
//   - d time.Duration
func (_e *MockTimeProvider_Expecter) Add(t interface{}, d interface{}) *MockTimeProvider_Add_Call {
	return &MockTimeProvider_Add_Call{Call: _e.mock.On("Add", t, d)}
}

func (_c *MockTimeProvider_Add_Call) Run(run func(t time.Time, d time.Duration)) *MockTimeProvider_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockTimeProvider_Add_Call) Return(_a0 time.Time) *MockTimeProvider_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeProvider_Add_Call) RunAndReturn(run func(time.Time, time.Duration) time.Time) *MockTimeProvider_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function with no fields
func (_m *MockTimeProvider) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTimeProvider_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTimeProvider_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockTimeProvider_Expecter) Now() *MockTimeProvider_Now_Call {
	return &MockTimeProvider_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockTimeProvider_Now_Call) Run(run func()) *MockTimeProvider_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimeProvider_Now_Call) Return(_a0 time.Time) *MockTimeProvider_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeProvider_Now_Call) RunAndReturn(run func() time.Time) *MockTimeProvider_Now_Call {
	_c.Call.Return(run)
	return _c
}

// ParseDuration provides a mock function with given fields: s
func (_m *MockTimeProvider) ParseDuration(s string) (porttime.Duration, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ParseDuration")
	}

	var r0 porttime.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (porttime.Duration, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(string) porttime.Duration); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(porttime.Duration)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTimeProvider_ParseDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseDuration'
type MockTimeProvider_ParseDuration_Call struct {
	*mock.Call
}

// ParseDuration is a helper method to define mock.On call
//   - s string
func (_e *MockTimeProvider_Expecter) ParseDuration(s interface{}) *MockTimeProvider_ParseDuration_Call {
	return &MockTimeProvider_ParseDuration_Call{Call: _e.mock.On("ParseDuration", s)}
}

func (_c *MockTimeProvider_ParseDuration_Call) Run(run func(s string)) *MockTimeProvider_ParseDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTimeProvider_ParseDuration_Call) Return(_a0 porttime.Duration, _a1 error) *MockTimeProvider_ParseDuration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTimeProvider_ParseDuration_Call) RunAndReturn(run func(string) (porttime.Duration, error)) *MockTimeProvider_ParseDuration_Call {
	_c.Call.Return(run)
	return _c
}

// Since provides a mock function with given fields: t
func (_m *MockTimeProvider) Since(t time.Time) time.Duration {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Since")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockTimeProvider_Since_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Since'
type MockTimeProvider_Since_Call struct {
	*mock.Call
}

// Since is a helper method to define mock.On call
//   - t time.Time
func (_e *MockTimeProvider_Expecter) Since(t interface{}) *MockTimeProvider_Since_Call {
	return &MockTimeProvider_Since_Call{Call: _e.mock.On("Since", t)}
}

func (_c *MockTimeProvider_Since_Call) Run(run func(t time.Time)) *MockTimeProvider_Since_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockTimeProvider_Since_Call) Return(_a0 time.Duration) *MockTimeProvider_Since_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeProvider_Since_Call) RunAndReturn(run func(time.Time) time.Duration) *MockTimeProvider_Since_Call {
	_c.Call.Return(run)
	return _c
}

// Sleep provides a mock function with given fields: d
func (_m *MockTimeProvider) Sleep(d time.Duration) {
	_m.Called(d)
}

// MockTimeProvider_Sleep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sleep'
type MockTimeProvider_Sleep_Call struct {
	*mock.Call
}

// Sleep is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockTimeProvider_Expecter) Sleep(d interface{}) *MockTimeProvider_Sleep_Call {
	return &MockTimeProvider_Sleep_Call{Call: _e.mock.On("Sleep", d)}
}

func (_c *MockTimeProvider_Sleep_Call) Run(run func(d time.Duration)) *MockTimeProvider_Sleep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockTimeProvider_Sleep_Call) Return() *MockTimeProvider_Sleep_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTimeProvider_Sleep_Call) RunAndReturn(run func(time.Duration)) *MockTimeProvider_Sleep_Call {
	_c.Run(run)
	return _c
}

// Until provides a mock function with given fields: t
func (_m *MockTimeProvider) Until(t time.Time) time.Duration {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Until")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockTimeProvider_Until_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Until'
type MockTimeProvider_Until_Call struct {
	*mock.Call
}

// Until is a helper method to define mock.On call
//   - t time.Time
func (_e *MockTimeProvider_Expecter) Until(t interface{}) *MockTimeProvider_Until_Call {
	return &MockTimeProvider_Until_Call{Call: _e.mock.On("Until", t)}
}

func (_c *MockTimeProvider_Until_Call) Run(run func(t time.Time)) *MockTimeProvider_Until_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockTimeProvider_Until_Call) Return(_a0 time.Duration) *MockTimeProvider_Until_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeProvider_Until_Call) RunAndReturn(run func(time.Time) time.Duration) *MockTimeProvider_Until_Call {
	_c.Call.Return(run)
	return _c
}

// WithTimeout provides a mock function with given fields: ctx, timeout
func (_m *MockTimeProvider) WithTimeout(ctx context.Context, timeout time.Duration) (context.Context, context.CancelFunc) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WithTimeout")
	}

	var r0 context.Context
	var r1 context.CancelFunc
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (context.Context, context.CancelFunc)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) context.Context); ok {
		r0 = rf(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) context.CancelFunc); ok {
		r1 = rf(ctx, timeout)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}

	return r0, r1
}

// MockTimeProvider_WithTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTimeout'
type MockTimeProvider_WithTimeout_Call struct {
	*mock.Call
}

// WithTimeout is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockTimeProvider_Expecter) WithTimeout(ctx interface{}, timeout interface{}) *MockTimeProvider_WithTimeout_Call {
	return &MockTimeProvider_WithTimeout_Call{Call: _e.mock.On("WithTimeout", ctx, timeout)}
}

func (_c *MockTimeProvider_WithTimeout_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockTimeProvider_WithTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockTimeProvider_WithTimeout_Call) Return(_a0 context.Context, _a1 context.CancelFunc) *MockTimeProvider_WithTimeout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTimeProvider_WithTimeout_Call) RunAndReturn(run func(context.Context, time.Duration) (context.Context, context.CancelFunc)) *MockTimeProvider_WithTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTimeProvider creates a new instance of MockTimeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimeProvider {
	mock := &MockTimeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
