with-expecter: true
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
recursive: true
all: true
packages:
  github.com/amirhossein-jamali/auth-guardian/internal/domain/port:
    config:
      dir: "mocks/port/{{.PackageName}}"
      outpkg: "{{.PackageName}}"
      mockname: "Mock{{.InterfaceName}}"
      filename: "{{.InterfaceName}}.go"
filename: "{{.InterfaceName}}.go"
dir: "mocks"
outpkg: "mocks"
inpackage: false