// Code generated by mockery. DO NOT EDIT.

package metrics

import mock "github.com/stretchr/testify/mock"

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

type MockRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecorder) EXPECT() *MockRecorder_Expecter {
	return &MockRecorder_Expecter{mock: &_m.Mock}
}

// IncCounter provides a mock function with given fields: name, tags
func (_m *MockRecorder) IncCounter(name string, tags map[string]string) {
	_m.Called(name, tags)
}

// MockRecorder_IncCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncCounter'
type MockRecorder_IncCounter_Call struct {
	*mock.Call
}

// IncCounter is a helper method to define mock.On call
//   - name string
//   - tags map[string]string
func (_e *MockRecorder_Expecter) IncCounter(name interface{}, tags interface{}) *MockRecorder_IncCounter_Call {
	return &MockRecorder_IncCounter_Call{Call: _e.mock.On("IncCounter", name, tags)}
}

func (_c *MockRecorder_IncCounter_Call) Run(run func(name string, tags map[string]string)) *MockRecorder_IncCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]string))
	})
	return _c
}

func (_c *MockRecorder_IncCounter_Call) Return() *MockRecorder_IncCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_IncCounter_Call) RunAndReturn(run func(string, map[string]string)) *MockRecorder_IncCounter_Call {
	_c.Run(run)
	return _c
}

// ObserveHistogram provides a mock function with given fields: name, value, tags
func (_m *MockRecorder) ObserveHistogram(name string, value float64, tags map[string]string) {
	_m.Called(name, value, tags)
}

// MockRecorder_ObserveHistogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveHistogram'
type MockRecorder_ObserveHistogram_Call struct {
	*mock.Call
}

// ObserveHistogram is a helper method to define mock.On call
//   - name string
//   - value float64
//   - tags map[string]string
func (_e *MockRecorder_Expecter) ObserveHistogram(name interface{}, value interface{}, tags interface{}) *MockRecorder_ObserveHistogram_Call {
	return &MockRecorder_ObserveHistogram_Call{Call: _e.mock.On("ObserveHistogram", name, value, tags)}
}

func (_c *MockRecorder_ObserveHistogram_Call) Run(run func(name string, value float64, tags map[string]string)) *MockRecorder_ObserveHistogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockRecorder_ObserveHistogram_Call) Return() *MockRecorder_ObserveHistogram_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_ObserveHistogram_Call) RunAndReturn(run func(string, float64, map[string]string)) *MockRecorder_ObserveHistogram_Call {
	_c.Run(run)
	return _c
}

// SetGauge provides a mock function with given fields: name, value, tags
func (_m *MockRecorder) SetGauge(name string, value float64, tags map[string]string) {
	_m.Called(name, value, tags)
}

// MockRecorder_SetGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGauge'
type MockRecorder_SetGauge_Call struct {
	*mock.Call
}

// SetGauge is a helper method to define mock.On call
//   - name string
//   - value float64
//   - tags map[string]string
func (_e *MockRecorder_Expecter) SetGauge(name interface{}, value interface{}, tags interface{}) *MockRecorder_SetGauge_Call {
	return &MockRecorder_SetGauge_Call{Call: _e.mock.On("SetGauge", name, value, tags)}
}

func (_c *MockRecorder_SetGauge_Call) Run(run func(name string, value float64, tags map[string]string)) *MockRecorder_SetGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockRecorder_SetGauge_Call) Return() *MockRecorder_SetGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_SetGauge_Call) RunAndReturn(run func(string, float64, map[string]string)) *MockRecorder_SetGauge_Call {
	_c.Run(run)
	return _c
}

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
