// Code generated by mockery. DO NOT EDIT.

package risk

import (
	context "context"

	risk "github.com/amirhossein-jamali/auth-guardian/internal/domain/port/risk"
	mock "github.com/stretchr/testify/mock"
)

// MockEvaluator is an autogenerated mock type for the Evaluator type
type MockEvaluator struct {
	mock.Mock
}

type MockEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluator) EXPECT() *MockEvaluator_Expecter {
	return &MockEvaluator_Expecter{mock: &_m.Mock}
}

// EvaluateLoginRisk provides a mock function with given fields: ctx, factors
func (_m *MockEvaluator) EvaluateLoginRisk(ctx context.Context, factors risk.LoginRiskFactors) (risk.Level, error) {
	ret := _m.Called(ctx, factors)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateLoginRisk")
	}

	var r0 risk.Level
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, risk.LoginRiskFactors) (risk.Level, error)); ok {
		return rf(ctx, factors)
	}
	if rf, ok := ret.Get(0).(func(context.Context, risk.LoginRiskFactors) risk.Level); ok {
		r0 = rf(ctx, factors)
	} else {
		r0 = ret.Get(0).(risk.Level)
	}

	if rf, ok := ret.Get(1).(func(context.Context, risk.LoginRiskFactors) error); ok {
		r1 = rf(ctx, factors)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEvaluator_EvaluateLoginRisk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateLoginRisk'
type MockEvaluator_EvaluateLoginRisk_Call struct {
	*mock.Call
}

// EvaluateLoginRisk is a helper method to define mock.On call
//   - ctx context.Context
//   - factors risk.LoginRiskFactors
func (_e *MockEvaluator_Expecter) EvaluateLoginRisk(ctx interface{}, factors interface{}) *MockEvaluator_EvaluateLoginRisk_Call {
	return &MockEvaluator_EvaluateLoginRisk_Call{Call: _e.mock.On("EvaluateLoginRisk", ctx, factors)}
}

func (_c *MockEvaluator_EvaluateLoginRisk_Call) Run(run func(ctx context.Context, factors risk.LoginRiskFactors)) *MockEvaluator_EvaluateLoginRisk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(risk.LoginRiskFactors))
	})
	return _c
}

func (_c *MockEvaluator_EvaluateLoginRisk_Call) Return(_a0 risk.Level, _a1 error) *MockEvaluator_EvaluateLoginRisk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEvaluator_EvaluateLoginRisk_Call) RunAndReturn(run func(context.Context, risk.LoginRiskFactors) (risk.Level, error)) *MockEvaluator_EvaluateLoginRisk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEvaluator creates a new instance of MockEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluator {
	mock := &MockEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
