// Code generated by mockery. DO NOT EDIT.

package password

import mock "github.com/stretchr/testify/mock"

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: _a0
func (_m *MockHasher) HashPassword(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHasher_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockHasher_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - _a0 string
func (_e *MockHasher_Expecter) HashPassword(_a0 interface{}) *MockHasher_HashPassword_Call {
	return &MockHasher_HashPassword_Call{Call: _e.mock.On("HashPassword", _a0)}
}

func (_c *MockHasher_HashPassword_Call) Run(run func(_a0 string)) *MockHasher_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHasher_HashPassword_Call) Return(_a0 string, _a1 error) *MockHasher_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHasher_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockHasher_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: hashedPassword, _a1
func (_m *MockHasher) VerifyPassword(hashedPassword string, _a1 string) (bool, error) {
	ret := _m.Called(hashedPassword, _a1)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(hashedPassword, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedPassword, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hashedPassword, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHasher_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockHasher_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - _a1 string
func (_e *MockHasher_Expecter) VerifyPassword(hashedPassword interface{}, _a1 interface{}) *MockHasher_VerifyPassword_Call {
	return &MockHasher_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hashedPassword, _a1)}
}

func (_c *MockHasher_VerifyPassword_Call) Run(run func(hashedPassword string, _a1 string)) *MockHasher_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockHasher_VerifyPassword_Call) Return(_a0 bool, _a1 error) *MockHasher_VerifyPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHasher_VerifyPassword_Call) RunAndReturn(run func(string, string) (bool, error)) *MockHasher_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
