server:
  host: "0.0.0.0"
  port: 8080
  readTimeout: 5    # seconds
  writeTimeout: 10  # seconds
  idleTimeout: 120  # seconds

database:
  driver: "postgres"
  host: "postgres"  # Use container name for Docker
  port: "5432"
  username: "test_user"
  password: "test_password"
  database: "auth_guardian_test"
  sslMode: "disable"
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: 30  # minutes

jwt:
  accessSecret: "test_access_secret"
  refreshSecret: "test_refresh_secret"
  accessTTL: 15       # minutes
  refreshTTL: 24      # hours
  issuer: "auth-guardian"
  audience: "auth-guardian-api"
  maxConcurrent: 5    # maximum concurrent sessions per user
  allowedClockSkew: 30 # seconds

logger:
  level: "debug"
  format: "json"
  output: "stdout"
  timeFormat: "2006-01-02T15:04:05.000Z07:00"
  callerInfo: true
  enableAudit: true   # Enable audit logging for security events

redis:
  host: "redis"     # Use container name for Docker
  port: "6379"
  password: ""
  db: 0
  keyPrefix: "ag_test:"

auth:
  argon2:
    memory: 16384       # 16MB memory cost (16 * 1024)
    iterations: 1        # Time cost - minimum for testing speed
    parallelism: 1       # Number of threads - minimum for testing
    saltLength: 16       # Salt length in bytes
    keyLength: 32        # Hash length in bytes
  accessTokenSecret: "test_access_secret"
  refreshTokenSecret: "test_refresh_secret"
  accessTokenTTL: 15        # minutes
  refreshTokenTTL: 24       # hours
  maxSessionsPerUser: 5     # Maximum concurrent sessions per user
  sessionInactivityTTL: 30  # days