services:
  postgres:
    image: postgres:latest
    container_name: auth_guardian_postgres
    env_file:
      - ../configs/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_guardian_admin -d auth_guardian_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_guardian_network
  
  redis:
    image: redis:latest
    container_name: auth_guardian_redis
    command: redis-server --requirepass simplepassword123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "simplepassword123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_guardian_network
  
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: auth_guardian_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ../configs:/app/configs:ro
      - ./logs:/app/logs
    environment:
      CONFIG_PATH: /app/configs/
    env_file:
      - ../configs/app.env
      - ../configs/jwt.env
      - ../configs/redis.env
      - ../configs/db.env
      - ../configs/server.env
    restart: unless-stopped
    networks:
      - auth_guardian_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  auth_guardian_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: