// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	entity "github.com/amirhossein-jamali/auth-guardian/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOTPRepository is an autogenerated mock type for the OTPRepository type
type MockOTPRepository struct {
	mock.Mock
}

type MockOTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPRepository) EXPECT() *MockOTPRepository_Expecter {
	return &MockOTPRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, otp
func (_m *MockOTPRepository) Create(ctx context.Context, otp *entity.OTP) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OTP) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOTPRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *entity.OTP
func (_e *MockOTPRepository_Expecter) Create(ctx interface{}, otp interface{}) *MockOTPRepository_Create_Call {
	return &MockOTPRepository_Create_Call{Call: _e.mock.On("Create", ctx, otp)}
}

func (_c *MockOTPRepository_Create_Call) Run(run func(ctx context.Context, otp *entity.OTP)) *MockOTPRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OTP))
	})
	return _c
}

func (_c *MockOTPRepository_Create_Call) Return(_a0 error) *MockOTPRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.OTP) error) *MockOTPRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, otpID
func (_m *MockOTPRepository) Delete(ctx context.Context, otpID entity.ID) error {
	ret := _m.Called(ctx, otpID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ID) error); ok {
		r0 = rf(ctx, otpID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOTPRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - otpID entity.ID
func (_e *MockOTPRepository_Expecter) Delete(ctx interface{}, otpID interface{}) *MockOTPRepository_Delete_Call {
	return &MockOTPRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, otpID)}
}

func (_c *MockOTPRepository_Delete_Call) Run(run func(ctx context.Context, otpID entity.ID)) *MockOTPRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.ID))
	})
	return _c
}

func (_c *MockOTPRepository_Delete_Call) Return(_a0 error) *MockOTPRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_Delete_Call) RunAndReturn(run func(context.Context, entity.ID) error) *MockOTPRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockOTPRepository) DeleteExpired(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockOTPRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOTPRepository_Expecter) DeleteExpired(ctx interface{}) *MockOTPRepository_DeleteExpired_Call {
	return &MockOTPRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockOTPRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockOTPRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOTPRepository_DeleteExpired_Call) Return(_a0 int, _a1 error) *MockOTPRepository_DeleteExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) (int, error)) *MockOTPRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *MockOTPRepository) GetByPhoneNumber(ctx context.Context, phoneNumber string) (*entity.OTP, error) {
	ret := _m.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhoneNumber")
	}

	var r0 *entity.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.OTP, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.OTP); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OTP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPRepository_GetByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPhoneNumber'
type MockOTPRepository_GetByPhoneNumber_Call struct {
	*mock.Call
}

// GetByPhoneNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockOTPRepository_Expecter) GetByPhoneNumber(ctx interface{}, phoneNumber interface{}) *MockOTPRepository_GetByPhoneNumber_Call {
	return &MockOTPRepository_GetByPhoneNumber_Call{Call: _e.mock.On("GetByPhoneNumber", ctx, phoneNumber)}
}

func (_c *MockOTPRepository_GetByPhoneNumber_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockOTPRepository_GetByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOTPRepository_GetByPhoneNumber_Call) Return(_a0 *entity.OTP, _a1 error) *MockOTPRepository_GetByPhoneNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPRepository_GetByPhoneNumber_Call) RunAndReturn(run func(context.Context, string) (*entity.OTP, error)) *MockOTPRepository_GetByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, otp
func (_m *MockOTPRepository) Update(ctx context.Context, otp *entity.OTP) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OTP) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOTPRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - otp *entity.OTP
func (_e *MockOTPRepository_Expecter) Update(ctx interface{}, otp interface{}) *MockOTPRepository_Update_Call {
	return &MockOTPRepository_Update_Call{Call: _e.mock.On("Update", ctx, otp)}
}

func (_c *MockOTPRepository_Update_Call) Run(run func(ctx context.Context, otp *entity.OTP)) *MockOTPRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OTP))
	})
	return _c
}

func (_c *MockOTPRepository_Update_Call) Return(_a0 error) *MockOTPRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.OTP) error) *MockOTPRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPRepository creates a new instance of MockOTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPRepository {
	mock := &MockOTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
