// Code generated by mockery. DO NOT EDIT.

package idgenerator

import mock "github.com/stretchr/testify/mock"

// MockIDGenerator is an autogenerated mock type for the IDGenerator type
type MockIDGenerator struct {
	mock.Mock
}

type MockIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDGenerator) EXPECT() *MockIDGenerator_Expecter {
	return &MockIDGenerator_Expecter{mock: &_m.Mock}
}

// GenerateID provides a mock function with no fields
func (_m *MockIDGenerator) GenerateID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIDGenerator_GenerateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateID'
type MockIDGenerator_GenerateID_Call struct {
	*mock.Call
}

// GenerateID is a helper method to define mock.On call
func (_e *MockIDGenerator_Expecter) GenerateID() *MockIDGenerator_GenerateID_Call {
	return &MockIDGenerator_GenerateID_Call{Call: _e.mock.On("GenerateID")}
}

func (_c *MockIDGenerator_GenerateID_Call) Run(run func()) *MockIDGenerator_GenerateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDGenerator_GenerateID_Call) Return(_a0 string) *MockIDGenerator_GenerateID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIDGenerator_GenerateID_Call) RunAndReturn(run func() string) *MockIDGenerator_GenerateID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDGenerator creates a new instance of MockIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDGenerator {
	mock := &MockIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
