// Code generated by mockery. DO NOT EDIT.

package otp

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOTPService is an autogenerated mock type for the OTPService type
type MockOTPService struct {
	mock.Mock
}

type MockOTPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPService) EXPECT() *MockOTPService_Expecter {
	return &MockOTPService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: length
func (_m *MockOTPService) Generate(length int) string {
	ret := _m.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOTPService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockOTPService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - length int
func (_e *MockOTPService_Expecter) Generate(length interface{}) *MockOTPService_Generate_Call {
	return &MockOTPService_Generate_Call{Call: _e.mock.On("Generate", length)}
}

func (_c *MockOTPService_Generate_Call) Run(run func(length int)) *MockOTPService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockOTPService_Generate_Call) Return(_a0 string) *MockOTPService_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPService_Generate_Call) RunAndReturn(run func(int) string) *MockOTPService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, phoneNumber, code
func (_m *MockOTPService) Send(ctx context.Context, phoneNumber string, code string) error {
	ret := _m.Called(ctx, phoneNumber, code)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, phoneNumber, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockOTPService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
//   - code string
func (_e *MockOTPService_Expecter) Send(ctx interface{}, phoneNumber interface{}, code interface{}) *MockOTPService_Send_Call {
	return &MockOTPService_Send_Call{Call: _e.mock.On("Send", ctx, phoneNumber, code)}
}

func (_c *MockOTPService_Send_Call) Run(run func(ctx context.Context, phoneNumber string, code string)) *MockOTPService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOTPService_Send_Call) Return(_a0 error) *MockOTPService_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPService_Send_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOTPService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPService creates a new instance of MockOTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPService {
	mock := &MockOTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
