name: CI Testing Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      
      - name: Get dependencies
        run: go mod download
      
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  build:
    name: Verify Docker Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build containers
        run: |
          docker-compose -f docker/docker-compose.yml build
          
      - name: Verify containers start correctly
        run: |
          docker-compose -f docker/docker-compose.yml up -d
          # Wait for services to be healthy
          sleep 10
          # Check if containers are running
          docker-compose -f docker/docker-compose.yml ps
          # Show container logs if needed
          docker-compose -f docker/docker-compose.yml logs
          # Cleanup
          docker-compose -f docker/docker-compose.yml down